### ISSUE TITLE
About categories of target molecular

### ISSUE THREAD

**Issue by tszslovewanpu** [yuanqidu/M2Hub#3]
Hello, and excellent job! I have a question regarding the categorization. In section 4, the divisions between 'Learning on crystal structures' and 'Learning on molecular structures' caught my attention. Why are these two aspects separated? Doesn't crystal fall under the molecular category?

**Comment by yuanqidu** [comment]
Yes, crystals do fall under the molecule category, but they have special properties and uses such as periodicity. This basically follows why they are studied separately, e.g. proteins, RNAs, small molecule ligand, peptides are all biomolecules but they are studied differently.

**Comment by tszslovewanpu** [comment]
Got it, thank you ^.^

**Comment by yuanqidu** [comment]
Thanks!
