### ISSUE TITLE
scripts/uncompress.py is missing

### ISSUE THREAD

**Issue by wang-hlin** [yuanqidu/M2Hub#4]
Hi, thank you for making this tool! I noticed that scripts/uncompress.py is missing and it is used in download_data.py [L194](https://github.com/yuanqidu/M2Hub/blob/5e62a9afef949521efc3b203dc561d2ee8815521/scripts/download_data.py#L194). I believe this should follow the file with same name in Open Catalyst Project? Could you please add it to this repository?

**Comment by yuanqidu** [comment]
Thank you so much for catching it! Uploaded!
